timeout: 10800s
substitutions:
  _DYSON_APP_NAME: "dyson-taxi"
  _DYSON_TOPIC: "projects/pubsub-public-data/topics/taxirides-realtime"
steps:
  # [Set project Id throughout the repo]
- name: gcr.io/kpt-dev/kpt:latest
  id: "Set Project ID"
  args: ['cfg', 'set', '.', 'PROJECT_ID', '${PROJECT_ID}']

  # [Set the Pub/Sub topic to use
- name: gcr.io/kpt-dev/kpt:latest
  id: "Set Pub/Sub Topic"
  args: ['cfg', 'set', '.', 'TOPIC', '${_DYSON_TOPIC}']

  # [Set the name of the app to be deployed into GKE]
- name: gcr.io/kpt-dev/kpt:latest
  id: "Set App Name"
  args: ['cfg', 'set', '.', 'APP_NAME', '${_DYSON_APP_NAME}']

  # [Kick off Terraform deployment]
- name: "gcr.io/cloud-builders/gcloud"
  id: "deploy-cluster"
  dir: "setup"
  args:
  - "builds"
  - "submit"
  
  # [Build Dyson Container Image]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dyson:latest','.']

  # [Push Container Image to gcr]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/dyson:latest",]

  # [Deploy dyson manifests to GKE]
- name: 'gcr.io/cloud-builders/kubectl'
  waitFor:
    - deploy-cluster
  args: ['apply', '-f', './kubernetes/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dyson-cluster'