# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    customTemplate:
      template: "{{.DATE}}_{{.COMMIT}}"
      components:
      - name: DATE
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: COMMIT
        gitCommit:
          variant: AbbrevCommitSha
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: pulltop
    image: us-central1-docker.pkg.dev/jdnz-cloudrun-dev/ar-repo-us-central-1/dyson
  - context: websocketd
    image: us-central1-docker.pkg.dev/jdnz-cloudrun-dev/ar-repo-us-central-1/websocketd
  - context: cron
    image: us-central1-docker.pkg.dev/jdnz-cloudrun-dev/ar-repo-us-central-1/cron
  googleCloudBuild:
    projectId: jdnz-cloudrun-dev
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/namespace.yaml
    - kubernetes-manifests/*.yaml
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: jdnz-cloudrun-dev
