kind: ConfigMap
apiVersion: v1
metadata:
  name: topic-config-taxirides
  labels:
    app: dyson
  namespace: dyson
data:
  topic: projects/pubsub-public-data/topics/taxirides-realtime # kpt-set: ${topic}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: file-config-taxirides
  labels:
    app: dyson
  namespace: dyson
data:
  file: /data/output.json
