apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyson
  namespace: dyson
  annotations:
    "iam.gke.io/gcp-service-account": "pubsub@jdnz-cloudrun-dev.iam.gserviceaccount.com" # {"$ref":"#/definitions/io.k8s.cli.substitutions.project-id-sa"}
