apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyson-taxirides
  annotations:
    iam.gke.io/gcp-service-account: dyson-sa@my-project-id.iam.gserviceaccount.com # kpt-set: ${service-account}@${project-id}.iam.gserviceaccount.com
  namespace: dyson
  labels:
    app: dyson
