apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyson-taxi-app # {"$kpt-set":"app-name"}
  labels:
    app: dyson-taxi-app # {"$kpt-set":"app-name"}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyson-taxi-app # {"$kpt-set":"app-name"} 
  template:
    metadata:
      labels:
        app: dyson-taxi-app # {"$kpt-set":"app-name"} 
    spec:
      serviceAccountName: dyson
      containers:
      - name: dyson-taxi-app # {"$kpt-set":"app-name"}
        image: gcr.io/jdnz-dyson5/dyson:latest # {"$ref":"#/definitions/io.k8s.cli.substitutions.project-id-image"}
        ports:
        - protocol: TCP
          containerPort: 8080
        env:
        - name: SYMBOL
          valueFrom:
            configMapKeyRef:
              name: topic-config
              key: topic
        resources:
          limits:
            cpu: "300m"
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 200Mi
        imagePullPolicy: Always
