apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "dyson-taxi-hpa" # {"$kpt-set":"hpa-name"}
  labels:
    app: "dyson-taxi-app" # {"$kpt-set":"app-name"}
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "dyson-taxi-app" # {"$kpt-set":"app-name"}
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
