apiVersion: v1
kind: Service
metadata:
  name: dyson-taxi-service # {"$kpt-set":"service-name"}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dyson-taxi-app # {"$kpt-set":"app-name"}
  type: LoadBalancer
