apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyson
  annotations:
    "iam.gke.io/gcp-service-account": "dyson-sa@jdnz-dyson5.iam.gserviceaccount.com" # {"$ref":"#/definitions/io.k8s.cli.substitutions.project-id-sa"}
